name: CI/CD is easy!

on:
  push: 
    branches:
      - master

jobs:
  build:
    runs-on: ubunto-latest
    steps: 
      - uses: actions/checkout@v2 #get code
      - uses: actions/setup-node@v1 #setup node
        with:
          node-version: 12
      - run: npm ci #this means install
      - run: npm test
      - run: npm run build
      - run: npm run deploy #test, build, deploy
      
